### PR TITLE
verify MAC addr read from user input

### PR DESCRIPTION
**Pull request by gemesa**
Added MAC address verification.

Before (the script discarded the invalid input and kept the original addr):
```
$ sudo ./start-mon.sh wlp0s20f0u1
 --------------------------------
    start-mon.sh 20230206
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
    name  -  wlp0s20f0u1
    type  -  managed
    state -  DOWN
    addr  -  11:11:11:11:11:11
 --------------------------------

 Do you want to set a new addr? [y/N] y
 What addr do you want? ( e.g. 12:34:56:78:90:ab ) 123
```
```
 --------------------------------
    start-mon.sh 20230206
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
    name  -  wlan0mon
    type  -  monitor
    state -  DORMANT
    addr  -  11:11:11:11:11:11
    chan  -  1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
 --------------------------------

 Do you want to set the channel? [y/N] 

```

After (the script discards the invalid input and asks for it again):
```
$ sudo ./start-mon.sh wlp0s20f0u1
 --------------------------------
    start-mon.sh 20230206
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
    name  -  wlp0s20f0u1
    type  -  managed
    state -  DOWN
    addr  -  11:11:11:11:11:11
 --------------------------------

 Do you want to set a new addr? [y/N] y
 What addr do you want? ( e.g. 12:34:56:78:90:ab ) 123
 Invalid addr, try again: fgh
 Invalid addr, try again: 12:34:56:12:34:56
```
```
 --------------------------------
    start-mon.sh 20230206
 --------------------------------
    WiFi Interface:
             wlp0s20f0u1
 --------------------------------
    name  -  wlan0mon
    type  -  monitor
    state -  DORMANT
    addr  -  12:34:56:12:34:56
    chan  -  1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
 --------------------------------

 Do you want to set the channel? [y/N] 
```

### CODE REVIEW

**Comment by morrownr** [comment]
Thanks. That has been on my to-do list for a long time.

**Comment by morrownr** [comment]
If I just hit Enter when ask for the mac address:

```
 --------------------------------
    start-mon.sh 20230206
 --------------------------------
    WiFi Interface:
             wlx00c0caac47c7
 --------------------------------
command failed: No buffer space available (-105)
    name  -  
command failed: No buffer space available (-105)
    type  -  
    state -  DORMANT
command failed: No buffer space available (-105)
    addr  -  
command failed: No buffer space available (-105)
    chan  -  
 --------------------------------

```

**Comment by gemesa** [comment]
Are you sure that is the problem here? I can not reproduce it.

If I press enter here it just keeps the original address:
```
 Do you want to set a new addr? [y/N]
```
If I press `y`, leave the address empty and press `Enter` then it rejects the address:
```
 Do you want to set a new addr? [y/N] y
 What addr do you want? ( e.g. 12:34:56:78:90:ab ) 
 Invalid addr, try again: 
 Invalid addr, try again: 
 Invalid addr, try again: 
```

**Comment by gemesa** [comment]
Check out #6, it might help to debug your issue.

**Pull request merged**
